using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    public float moveSpeed = 3f;
    private Vector2 moveInput;
    private Rigidbody2D rb;
    private Animator animator;

    private void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();
    }

    private void Update()
    {
        moveInput.x = Input.GetAxisRaw("Horizontal"); // A, D or Left/Right
        moveInput.y = Input.GetAxisRaw("Vertical");    // W, S or Up/Down
        moveInput.Normalize();

        // π” μ• λ‹λ©”μ΄μ… μƒνƒ μ„¤μ •
        //bool isMoving = moveInput != Vector2.zero;
        bool isMoving = moveInput.sqrMagnitude > 0.01f;
        animator.SetBool("isMoving", isMoving);

        // π’΅ λ°©ν–¥ κ΄€λ ¨ νλΌλ―Έν„°λ„ μ„¤μ •
        animator.SetFloat("MoveX", moveInput.x);
        animator.SetFloat("MoveY", moveInput.y);
    }

    private void FixedUpdate()
    {
        rb.MovePosition(rb.position + moveInput * moveSpeed * Time.fixedDeltaTime);
    }
}
